# Generated by Django 5.1 on 2025-12-02 07:47

import apps.core.enums
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, unique=True)),
                ('status', models.IntegerField(default=apps.core.enums.Status['CREATED'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('event_category', models.CharField(choices=[('activity', 'Activity'), ('event', 'Event'), ('roadmap', 'Roadmap')], default='event', max_length=20)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('seminar', 'Seminar'), ('site-visit', 'Site Visit'), ('competition', 'Competition'), ('edificio', 'Edificio'), ('other', 'Other')], default='other', max_length=20)),
                ('activity_status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing')], default='upcoming', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_details', models.JSONField(blank=True, default=dict, null=True)),
                ('attendees_count', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured events appear on homepage')),
                ('speaker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('speaker_info', models.TextField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='For multi-day events', null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, unique=True)),
                ('status', models.IntegerField(default=apps.core.enums.Status['CREATED'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as cover image for the event')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='core.images')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='events.events')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['-is_cover', 'display_order'],
            },
        ),
    ]
