# Generated by Django 5.1 on 2025-12-02 07:47

import apps.core.enums
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid6, editable=False, unique=True)),
                ('status', models.IntegerField(default=apps.core.enums.Status['CREATED'])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_hod', models.BooleanField(default=False, help_text='Head of Department')),
                ('is_faculty', models.BooleanField(default=False, help_text='Faculty member')),
                ('is_active', models.BooleanField(default=True, help_text='Currently active member')),
                ('display_order', models.IntegerField(default=0, help_text='Order in team listing')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('committee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_committee', to='core.dropdown')),
                ('profile_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_image', to='core.images')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_role', to='core.dropdown')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-is_hod', '-is_faculty', '-featured', 'display_order', 'name'],
            },
        ),
    ]
